### ISSUE TITLE
Code::Stats Plugin will not uninstall

### ISSUE THREAD

**Issue by gmctec** [p0358/notepadpp-CodeStats#23]
I installed Code::Stats not realizing I had to get an API key.  I don't want to do that.  Tried to uninstall the plugin.  
Code::Stats will not uninstall (it goes thru the motions, but is still present after notepad++ restart. 
Now, the itimetracker plugin (company that developed Code::Stats) gives me TWO (not 1 but 2 seperate ) Windows demanding an API key upon startup.  I can't get rid of it.  

I have tried steps to manually uninstall, I still get the pop-up windows on restart.  
I have tried totally uninstalling, then reinstalling Notepad++, Code:Stats still remains.  

Code::Stats by iTimetracker appears to behave like a virus.  
It demands your attention and money (to get the API key) to make being pestered go away.  
Once you install it, you can never get rid of it, and it will pester you forever.

**Comment by p0358** [comment]
Not sure what's "itimetracker", but Code::Stats is sponsored by company called Vincit, and this plugin was written by me, who's not associated with them. I'm especially confused about this, because I cannot find any company of plugin with the name of "iTimetracker".
The plugin can be uninstalled by simply removing the DLL file from `%appdata%\plugins\Notepad++` in case the Notepad++'s uninstall feature is broken for whatever reason.

The API key is required, because Code::Stats is an online service, able to collect your XP from various editors and machines, and doing it this way is the only way feasible. Local stats and some kind of display of them would be troublesome and would bloat the plugin unnecessarily. The data sent consists of "pulses" that contain a list of languages used and the amount of keystrokes typed within each, which can be verified by checking both the source code, API docs and by sniffing the communication.

> It demands your attention and money (to get the API key) to make being pestered go away.

That is factually untrue, the service is free of charge and open source (and always has been), and the API key needs to be generated on the site to identify the user and machine to which assign the pulses to.

The box asking for key pops up after installation before it's set in order to setup the plugin, because without doing that, all the data is scraped, and it wouldn't make any sense to remain in such state.

**Comment by p0358** [comment]
If the uninstall button within Notepad++ doesn't work, then it's a bug that needs to be reported upstream in Notepad++, as the uninstallation process isn't handled by the plugins in any way
