### ISSUE TITLE
Code Stats version 1.1.0 - Suggests updating to previous version v1.0.1

### ISSUE THREAD

**Issue by cengbrecht** [p0358/notepadpp-CodeStats#25]
Fresh install from the Plugin Admin causes the API to not work.
Installing the dll from the repo directly causes the plugin to notify you of an update to the previous version from Notepad++'s plugin repo.

**To Reproduce**
1. Install plugin from Plugins Admin in Notepad++
2. Update Plugin from Github repo (x64) - https://github.com/p0358/notepadpp-CodeStats/releases/tag/v1.1.0
3. Replace DLL file
4. Open Notepad++ after update, and you should get the message. As I get it on both computers.

**Expected behavior**
Close the Notepad++ window work without update message.

**Screenshots**
![image](https://user-images.githubusercontent.com/1149435/198153810-ae53ba03-e3da-418e-9d8d-589d1d502194.png)

**Desktop:**
 - OS: Windows 10 - 21H2 (Latest)
 - Version 19044.2130

**Additional context**
Otherwise I am SUPER happy with the plugin and have just started on my Github and Programming journey.

**Comment by cengbrecht** [comment]
Decided my message was not adequate. 
Added a few details, and organized according to a template.

**Comment by p0358** [comment]
This could be considered kinda expected, since for now the version in Plugin Admin isn't updated (they'll update it only after next version of Notepad++ is released sadly), so it's a choice of either people who update manually getting this message, or everyone else with the old version. So I made the choice to have it this way for now, until the new version appears on Plugin Admin.

However this does point out the issue that version `1.1.0` is indeed newer than `1.0.1`, while the update check simply checks the version value is different instead of comparing it properly and displays this message. I'll see if I can fix this and add a proper comparison before they release newer Notepad++...

**Comment by cengbrecht** [comment]
Oh, so the check is happening in the plugin, but the version issue for latest is with Notepad++?

That's interesting. 
I appreciate the clarification. 

And, if I may ask, what language is the update check in?

**Comment by p0358** [comment]
> Oh, so the check is happening in the plugin, but the version issue for latest is with Notepad++?

Yeah, the plugin checks the version on its own, but the latest version isn't available in the Plugins Admin, as they ship the list of plugins with each Notepad++ update statically.

Back when I coded the plugin along with its update check, the plugin downloader used to be a separate module in Notepad++ which would always download latest version of the plugin list which used to make this a non-issue, however in the meantime they replaced it with a different system due to drama and hosting problems they had due to big amount of traffic (the drama backstory was that one company agreed to sponsor it in exchange of a banner and N++ devs did not like that at all)

> And, if I may ask, what language is the update check in?

C#, as the rest of the plugin (the plugin is using an adapter interface to work with Notepad++ which is written in C++)

**Comment by cengbrecht** [comment]
Thats cool, I would be happy to try to help, but I don't even know C++ yet. 
Literally working on it right now hahaha. :)

Thanks again.
