### ISSUE TITLE
WakaTime Notepad++ Plugin Failure

### ISSUE THREAD

**Issue by bylickilabs** [p0358/notepadpp-CodeStats#26]

**Comment by p0358** [comment]
Hello. I have no idea since this plugin right here is for Code::Stats service, not WakaTime -> https://codestats.net/

This service is similar in ways, but not the same. It counts only amount of keystrokes, not time spent in projects.

While this plugin was indeed originally based on WakaTime's plugin, a lot of things have internally changed here, both in terms of configuration, and especially in terms of how data is sent to the backend.

I suggest you report your issue in the correct repo for their plugin: https://github.com/wakatime/notepadpp-wakatime
